# Generated by Django 6.0 on 2026-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('premium', 'Premium Subscription'), ('session', 'Clinical Session')], default='session', max_length=20),
        ),
    ]
