# Generated by Django 6.0 on 2026-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
