# Generated by Django 6.0 on 2026-04-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_mpesa_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mpesa_full_name',
        ),
    ]
