# Generated by Django 6.0 on 2026-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Counselor'), ('clinical', 'Clinical Psychologist'), ('family', 'Family & Marriage Therapist'), ('addiction', 'Addiction Specialist'), ('child', 'Child & Adolescent Therapist'), ('trauma', 'Trauma Specialist')], default='general', max_length=50, null=True),
        ),
    ]
