# Generated by Django 6.0 on 2026-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
