# Generated by Django 6.0 on 2026-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_high_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Counselor'), ('clinical', 'Clinical Psychologist'), ('family', 'Family & Marriage Therapist'), ('addiction', 'Addiction Specialist'), ('child', 'Child & Adolescent Therapist'), ('trauma', 'Trauma Specialist')], max_length=50, null=True),
        ),
    ]
