# Generated by Django 6.0 on 2026-01-16 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('depression', 'Depression (PHQ-9)'), ('anxiety', 'Anxiety (GAD-7)'), ('bipolar', 'Bipolar Disorder'), ('substance', 'Substance Use')], default='depression', max_length=20)),
                ('score', models.IntegerField()),
                ('severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
