# Generated by Django 6.0 on 2026-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
